# -*- coding: utf-8 -*-
"""SML1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JiKzCsfBFBV4F7IRYZAaWGLWakhyi6Sa

# Importing Modules
"""

import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import math
from math import *

"""# Question 1"""

mu1 = 2
variance1 = 1
sigma1 = math.sqrt(variance1)
x1 = np.linspace(mu1 - 4*sigma1, mu1 + 4*sigma1, 100)
plt.xlabel("x")
plt.ylabel("P(x|w1)")
plt.plot(x1, stats.norm.pdf(x1, mu1, sigma1), color = "green")
plt.title('Likelihood')
plt.show()

mu2 = 5
variance2 = 1
sigma2 = math.sqrt(variance2)
x2 = np.linspace(-1, mu2 + 4*sigma2, 100)
plt.xlabel("x")
plt.ylabel("P(x|w2)")
plt.title('Likelihood')
plt.plot(x2, stats.norm.pdf(x2, mu2, sigma2), color = "red")
plt.show()

plt.plot(x1, stats.norm.pdf(x1, mu1, sigma1), color = "green")
plt.plot(x2, stats.norm.pdf(x2, mu2, sigma2), color = "red")
plt.ylabel("P(x|wi)")
plt.xlabel("x")
plt.title('Likelihoods in same plot')
plt.legend(["P(x|w1)", "P(x|w2)"])
plt.show()

x = np.linspace(-4, 4, 100)
y1 = (1/pow(2*pi,0.5))*(e**(-0.5*(x-2)*(x-2)))*1.0
y2 = (1/pow(2*pi,0.5))*(e**(-0.5*(x-5)*(x-5)))*1.0
fig = plt.figure(figsize = (10, 5))
y = y1/y2
plt.xlabel('x')
plt.ylabel('P(x|w1)/P(x|w2)')
plt.title('Ratio of Likelihoods')
plt.plot(x, y)
plt.show()

"""# Question 3(b)"""

x = np.linspace(-100, 100, 100)
y1 = 1/((x-3)*(x-3))
y2 = 1/((x-5)*(x-5))
y = y1/(y1+y2)
fig = plt.figure(figsize = (10, 5))
plt.xlabel('x')
plt.ylabel('P(w1|x)')
plt.title('Posterior Probability')
plt.plot(x, y)
plt.show()