# -*- coding: utf-8 -*-
"""SML3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QZkNaBlPDYE_e4Xo5Xd9JN1s0GABR_MM
"""

from google.colab import drive
drive.mount('/content/drive/')

import tarfile
import os
import numpy as np
import pickle
from google.colab.patches import cv2_imshow
import cv2 as cv

"""#Question1

#(a)
"""

# open file
file = tarfile.open('/content/drive/MyDrive/SML/cifar-10-python.tar.gz')
# extract files
file.extractall('Files')
# close file
file.close()

def unpickle(file):
  with open(file, 'rb') as fo:
    dict = pickle.load(fo, encoding='latin1')
    return dict

def displayImage(image):
  image = image.reshape(3,32,32)
  image = image.transpose(1,2,0)
  image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
  cv2_imshow(image)

def visualise(num):
  path = '/content/Files/cifar-10-batches-py/data_batch_'
  path += str(num)
  print('data_batch_'+str(num))
  data = unpickle(path)
  for i in range(10):
    print('Class: '+str(i))
    count = 0
    for j in range(len(data['labels'])):
      if data['labels'][j]==i:
        count += 1
        displayImage(data['data'][j])
        if count==5:
          break

for i in range(5):
  visualise(i+1)